version: 2

updates:
  - package-ecosystem: 'npm'
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /docs/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /tests-e2e/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a17/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a18/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a19/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a20/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/jasmine/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/jest/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/min/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/nx/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'docker'
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'
