release:
  branches:
    - master
    - name: issues/a13
      prerelease: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: docs
          scope: README
          release: patch
  - - '@semantic-release/exec'
    - prepareCmd: npm install && npm run lint && npm run ts:check && npm run build
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - pkgRoot: dist/libs/ng-mocks
      tarballDir: tmp
      npmPublish: false
  - - '@semantic-release/github'
    - assets:
        - tmp/*.tgz
      successComment: >-
        [v${nextRelease.version}](https://github.com/ike18t/ng-mocks/releases/tag/v${nextRelease.version})
        has been released and contains a fix for the issue.
        Feel free to reopen the issue or to submit a new one if you meet any problems.
      failTitle: false
      failComment: false
      labels: false
      releasedLabels:
        - released
        - >-
          v${nextRelease.version}
  - - '@semantic-release/git'
    - message: 'chore(release): v${nextRelease.version}'
