services:
  ng-mocks:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - .:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  docs:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./docs:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  e2e:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./tests-e2e:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a17:
    image: satantime/puppeteer-node:20.20.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/a17:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a18:
    image: satantime/puppeteer-node:20.20.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/a18:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a19:
    image: satantime/puppeteer-node:22.22.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/a19:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a20:
    image: satantime/puppeteer-node:22.22.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/a20:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a21:
    image: satantime/puppeteer-node:22.21.1
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/a21:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  jasmine:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/jasmine:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  jest:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/jest:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  min:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/min:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  nx:
    image: satantime/puppeteer-node:24.13.0
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./e2e/nx:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

volumes:
  cache:
  gyp:
  npm:
