version|e2e/a5es5/src/app|5
version|e2e/a5es2015/src/app|5
version|e2e/a6/src/app|6
version|e2e/a7/src/app|7
version|e2e/a8/src/app|8
version|e2e/a9/src/app|9
version|e2e/a10/src/app|10
version|e2e/a11/src/app|11
version|e2e/a12/src/app|12
version|e2e/a13/src/app|13
version|e2e/a14/src/app|14
version|e2e/a15/src/app|15
version|e2e/a16/src/app|16
version|e2e/a17/src/app|17
version|e2e/a18/src/app|18
version|e2e/a19/src/app|19
version|e2e/a20/src/app|20
version|e2e/a21/src/app|21
version|e2e/a22/src/app|22
version|e2e/jasmine/src/app|21
version|e2e/jest/src/app|21
version|e2e/min/src/app|21
version|e2e/nx/src/app|21

file|tests-e2e/src/app/**|strip=tests-e2e/src/app
