version|e2e/a5es5/src/test|5
version|e2e/a5es2015/src/test|5
version|e2e/a6/src/test|6
version|e2e/a7/src/test|7
version|e2e/a8/src/test|8
version|e2e/a9/src/test|9
version|e2e/a10/src/test|10
version|e2e/a11/src/test|11
version|e2e/a12/src/test|12
version|e2e/a13/src/test|13
version|e2e/a14/src/test|14
version|e2e/a15/src/test|15
version|e2e/a16/src/test|16
version|e2e/a17/src/test|17
version|e2e/a18/src/test|18
version|e2e/a19/src/test|19
version|e2e/a20/src/test|20
version|e2e/a21/src/test|21
version|e2e/a22/src/test|22
version|e2e/nx/src/test|21

feature|ivy|versions=9+
feature|standalone|versions=14+
feature|typedForms|versions=14+
feature|routerFns|versions=14+
feature|injectFn|versions=14+
feature|hostDirectives|versions=15+
feature|signals|versions=16+
feature|hydration|versions=16+
feature|provideZoneChangeDetection|versions=16+
feature|controlFlow|versions=17+
feature|defer|versions=17+
feature|signalInputs|versions=17+
feature|signalQueries|versions=17+
feature|outputFn|versions=17+
feature|letBlock|versions=18+
feature|eventReplay|versions=18+
feature|standaloneDefaultTrue|versions=19+
feature|strictStandalone|versions=19+
feature|incrementalHydration|versions=19+
feature|routeRenderMode|versions=19+
feature|linkedSignal|versions=19+
feature|resource|versions=19+
feature|zonelessExperimental|versions=19+
feature|zoneless|versions=20+
feature|httpResource|versions=20+
feature|signalForms|versions=21+

file|examples/TestRoutingGuard/can-*.spec.ts|features=routerFns
file|examples/TestRoutingResolver/fn.spec.ts|features=routerFns
file|tests/issue-4282/*.ts|versions=6+
file|examples/TestRoutingGuard/test.spec.ts|versions=6+
file|examples/TestRoutingResolver/test.spec.ts|versions=6+
file|tests/mock-service/observable.spec.ts|versions=6+
file|tests/**
file|examples/**
